exports.STATUS_CODES = {

    // SUCCESS
    SUCCESS: 200,
    CREATED: 201,

    // CLIENT ERROR
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 403,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    VALIDATION_ERROR: 422,

    // SERVER ERROR
    SERVER_ERROR: 500,
    BAD_GATEWAY: 502,
}